# Generated by Django 5.1.6 on 2025-04-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='resolution_note',
            field=models.TextField(blank=True, null=True, verbose_name='Примітка щодо рішення'),
        ),
    ]
