# Generated by Django 5.1.6 on 2025-04-08 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0015_donationcampaign_moderation_reason_and_more'),
        ('reports', '0002_report_resolution_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='fundraiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_reports', to='fundraising.donationcampaign'),
        ),
    ]
