# Generated by Django 5.1.6 on 2025-04-08 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0016_remove_donationcampaign_reports'),
        ('reports', '0003_alter_report_fundraiser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='fundraiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='fundraising.donationcampaign'),
        ),
    ]
