# Generated by Django 5.1.6 on 2025-04-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_fundraiser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'Звіт', 'verbose_name_plural': 'Звіти'},
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='report',
            name='resolution_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'На розгляді'), ('approved', 'Схвалено'), ('rejected', 'Відхилено')], default='pending', max_length=10),
        ),
    ]
