# Generated by Django 5.1.6 on 2025-04-09 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0017_remove_donationcampaign_moderation_reason_and_more'),
        ('reports', '0005_alter_report_options_alter_report_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='fundraiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fundraising.donationcampaign'),
        ),
    ]
