# Generated by Django 5.1.6 on 2025-04-10 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0019_alter_donationcampaign_options_and_more'),
        ('reports', '0008_alter_report_fundraiser_alter_report_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='fundraiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='fundraising.donationcampaign'),
        ),
    ]
