# Generated by Django 5.1.6 on 2025-02-26 21:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0002_donationcampaign_category_donationcampaign_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationcampaign',
            options={'ordering': ['-created_at'], 'verbose_name': 'Кампанія збору коштів', 'verbose_name_plural': 'Кампанії збору коштів'},
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення'),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Зібрана сума'),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершення'),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='help_type',
            field=models.CharField(choices=[('money', 'Фінансова допомога'), ('volunteer', 'Волонтерська допомога'), ('both', 'Обидва типи')], default='money', max_length=50, verbose_name='Тип допомоги'),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Місцезнаходження'),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('active', 'Активна'), ('paused', 'Призупинена'), ('completed', 'Завершена'), ('cancelled', 'Скасована')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення'),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='urgency',
            field=models.CharField(choices=[('urgent', 'Терміново'), ('non-urgent', 'Не терміново')], default='non-urgent', max_length=20, verbose_name='Терміновість'),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='category',
            field=models.CharField(choices=[('health', "Здоров'я"), ('social', 'Соціальна допомога'), ('education', 'Освіта та наука'), ('ecology', 'Екологія та тварини'), ('other', 'Інше')], default='other', max_length=50, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='contact_info',
            field=models.CharField(max_length=200, verbose_name='Контактна інформація'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='creator_name',
            field=models.CharField(max_length=100, verbose_name="Ім'я організатора"),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='donation_link',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання для пожертв'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='evidence',
            field=models.TextField(blank=True, null=True, verbose_name='Опис підтвердження'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='evidence_file',
            field=models.FileField(blank=True, null=True, upload_to='evidence/', verbose_name='Файл підтвердження'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='evidence_link',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на підтвердження'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цільова сума'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='campaign_images/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Назва кампанії'),
        ),
    ]
