# Generated by Django 5.1.6 on 2025-03-26 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0005_remove_donationcampaign_urgency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationcampaign',
            name='user',
        ),
    ]
