# Generated by Django 5.1.6 on 2025-03-27 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0010_populate_creator_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcampaign',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата видалення'),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Видалено'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Створив'),
        ),
    ]
