# Generated by Django 5.1.6 on 2025-03-27 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0011_donationcampaign_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationcampaign',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='donationcampaign',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Створив'),
        ),
    ]
