# Generated by Django 5.1.6 on 2025-04-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0013_mockdonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcampaign',
            name='needs_moderation',
            field=models.BooleanField(default=False, verbose_name='Потребує модерації'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('active', 'Активний'), ('paused', 'Призупинений'), ('completed', 'Завершений'), ('cancelled', 'Скасований')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
