# Generated by Django 5.1.6 on 2025-04-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0014_donationcampaign_needs_moderation_and_more'),
        ('reports', '0002_report_resolution_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcampaign',
            name='moderation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина модерації'),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='pause_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='reports',
            field=models.ManyToManyField(blank=True, related_name='reported_campaigns', to='reports.report'),
        ),
    ]
