# Generated by Django 5.1.6 on 2025-04-08 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0015_donationcampaign_moderation_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationcampaign',
            name='reports',
        ),
    ]
