# Generated by Django 5.1.6 on 2025-04-08 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0016_remove_donationcampaign_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationcampaign',
            name='moderation_reason',
        ),
        migrations.RemoveField(
            model_name='donationcampaign',
            name='pause_reason',
        ),
    ]
