# Generated by Django 5.1.6 on 2025-04-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0017_remove_donationcampaign_moderation_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('pending', 'На розгляді'), ('active', 'Активний'), ('paused', 'Призупинений'), ('completed', 'Завершений'), ('cancelled', 'Скасований')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
