# Generated by Django 5.1.6 on 2025-04-10 18:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0018_alter_donationcampaign_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationcampaign',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='warnings_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='category',
            field=models.CharField(choices=[('health', "Здоров'я"), ('social', 'Соціальна допомога'), ('education', 'Освіта та наука'), ('ecology', 'Екологія та тварини'), ('other', 'Інше')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='contact_info',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='donation_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='evidence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='evidence_file',
            field=models.FileField(blank=True, null=True, upload_to='evidence/'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='evidence_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='help_type',
            field=models.CharField(choices=[('money', 'Фінансова допомога'), ('volunteer', 'Волонтерська допомога'), ('both', 'Обидва типи')], default='money', max_length=50),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='campaign_images/'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='needs_moderation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('pending', 'На розгляді'), ('active', 'Активний'), ('paused', 'Призупинений'), ('completed', 'Завершений'), ('cancelled', 'Скасований')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
