# Generated by Django 5.1.6 on 2025-04-10 18:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0019_alter_donationcampaign_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MockDonation',
            new_name='Donation',
        ),
    ]
