# Generated by Django 5.1.6 on 2025-04-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0021_remove_donation_mock_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcampaign',
            name='status',
            field=models.CharField(choices=[('pending', 'На розгляді'), ('active', 'Активний'), ('paused', 'Призупинений'), ('completed', 'Завершений'), ('cancelled', 'Скасований')], default='pending', max_length=20),
        ),
    ]
