# Generated by Django 5.1.6 on 2025-04-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0022_alter_donationcampaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcampaign',
            name='previous_status',
            field=models.CharField(blank=True, help_text='Попередній статус перед зміною', max_length=20, null=True),
        ),
    ]
