# Generated by Django 5.1.6 on 2025-04-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0023_donationcampaign_previous_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcampaign',
            name='city',
            field=models.CharField(choices=[('kyiv', 'Київ'), ('lviv', 'Львів'), ('kharkiv', 'Харків'), ('odesa', 'Одеса'), ('dnipro', 'Дніпро'), ('other', 'Інше місто')], default='other', max_length=20, verbose_name='Місто'),
        ),
    ]
